on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.0
      - run: go test
      - run: go test -bench . | tee bench.txt
      - uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: go
          output-file-path: bench.txt
          auto-push: true
